@HostAddress = http://localhost:5185
@PATH = api/honorario

### ObterTodos
GET {{HostAddress}}/{{PATH}}
Accept: application/json

### ObterPorId
GET {{HostAddress}}/{{PATH}}/660d2831-d12c-4896-ad80-76aa63b752a2
Accept: application/json

### Adicionar
POST {{HostAddress}}/{{PATH}}
Content-Type: application/json

{
  "descricao": "Teste",
  "rendaMensal": 8500.00,
  "servicoContabil": "170",
  "simplesNacional": 6,
  "valorVR": 35.50,
  "valorVT": "12.40"
}

### Remover
DELETE {{HostAddress}}/{{PATH}}/93959fbd-5f45-415b-a8fa-131853c676f6
Content-Type: application/json