# @HostAddress = http://localhost:5185
@HostAddress = http://localhost:8080
@PATH = api/honorario

### ObterTodos
GET {{HostAddress}}/{{PATH}}
Accept: application/json

### ObterPorId
GET {{HostAddress}}/{{PATH}}/69a8ee0a-e56d-4ef0-979d-da1f85d7f700
Accept: application/json

### Adicionar
POST {{HostAddress}}/{{PATH}}
Content-Type: application/json

{
  "descricao": "Proposta 01",
  "rendaMensal": 8500.00,
  "servicoContabil": 179.00,
  "simplesNacional": 6,
  "valorVR": 0,
  "valorVT": 0
}

### Remover
DELETE {{HostAddress}}/{{PATH}}/93959fbd-5f45-415b-a8fa-131853c676f6
Content-Type: application/json