version: "3.8"

services:
  calculo-honorario-db:
    image: postgres
    container_name: calculo-honorario-db
    volumes:
      - ../database/postgres/entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
      - ../database/postgres/initial.sql:/sql/initial.sql
      - ../database/postgres/initial.sql:/sql/vr-vt-nullable.sql
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: "postgres@SQL"

  calculo-honorario-api:
    image: calculo-honorario-api:latest
    container_name: calculo-honorario-api
    build:
      context: ../src/CalculoHonorario.Api
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: http://+:8080
      USE_HTTPS_REDIRECTION: "false"
      CUSTOMCONNSTR_DefaultConnection: "Server=calculo-honorario-db;Database=calculohonorario;User Id=postgres;Password=postgres@SQL;Pooling=true"
      AppSettings__DatabaseType: postgres
    depends_on:
      - calculo-honorario-db
