// <auto-generated />
using System;
using CalculoHonorario.Api.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CalculoHonorario.Api.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240502165652_VR-VT-Nullable")]
    partial class VRVTNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CalculoHonorario.Api.Domain.Entities.Honorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CadastradoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Fgts")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Inss")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Irpf")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("LucroBruto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("LucroLiquido")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ProLaboreBruto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ProLaboreLiquido")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ProvisaoDecimoTerceiro")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ProvisaoFerias")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ServicoContabil")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SimplesNacional")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ValeRefeicao")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ValeTransporte")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorHonorario")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("Honorarios");
                });
#pragma warning restore 612, 618
        }
    }
}
