// <auto-generated />
using System;
using CalculoHonorario.Api.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculoHonorario.Api.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalculoHonorario.Api.Domain.Models.Honorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CadastradoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Fgts")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Inss")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Irpf")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("LucroBruto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("LucroLiquido")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ProLaboreBruto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ProLaboreLiquido")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ProvisaoDecimoTerceiro")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ProvisaoFerias")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ServicoContabil")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SimplesNacional")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ValeRefeicao")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ValeTransporte")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ValorHonorario")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("Honorarios");
                });
#pragma warning restore 612, 618
        }
    }
}
