// <auto-generated />
using System;
using CalculoHonorario.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculoHonorario.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("CalculoHonorario.Business.Models.Honorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CadastradoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Fgts")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Inss")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Irpf")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LucroBruto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LucroLiquido")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProLaboreBruto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProLaboreLiquido")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProvisaoDecimoTerceiro")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProvisaoFerias")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServicoContabil")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SimplesNacional")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValeRefeicao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValeTransporte")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorHonorario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Honorarios");
                });
#pragma warning restore 612, 618
        }
    }
}
